version: '3.7'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data

  bot:
    build: 
      context: ./src/bot
      dockerfile: Dockerfile
    restart: always
    environment:
      - API_KEY=${API_KEY}

  site:
    build: 
      context: ./src/site
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - db
    ports:
      - 8000:8000
    links:
      - db:db
    volumes:
      - ./src/site:/app

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    depends_on: 
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 8080:80
    links:
      - db:db

  functions:
    build: 
      context: ./src/functions
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - db
    links:
      - db:db