# Generated by Django 4.1.4 on 2022-12-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userclient",
            name="user_document",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user.client",
            ),
        ),
    ]
