# Generated by Django 4.1.5 on 2023-01-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userclient_user_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclient',
            name='user_document',
        ),
        migrations.AddField(
            model_name='userclient',
            name='user_document',
            field=models.ManyToManyField(to='user.client'),
        ),
    ]
