# Generated by Django 4.1.5 on 2023-01-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('street_number', models.CharField(max_length=10, null=True)),
                ('neighborhood', models.CharField(max_length=100, null=True)),
                ('complement', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('target', models.CharField(max_length=20)),
                ('sponsorship_name', models.CharField(max_length=20)),
                ('sponsorship_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('document', models.CharField(max_length=14, null=True)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20, null=True)),
                ('delivery_by', models.CharField(max_length=20, null=True)),
                ('delivery_date_time', models.DateTimeField(null=True)),
                ('observations', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('full_description', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('liabilities', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ifood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=20)),
                ('order_timing', models.CharField(max_length=20)),
                ('sales_channel', models.CharField(max_length=30)),
                ('extra_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IfoodClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_count', models.IntegerField(null=True)),
                ('segmentation', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('bank_account', models.CharField(max_length=20, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('image_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('unit_price', models.FloatField()),
                ('addition', models.FloatField()),
                ('price', models.FloatField()),
                ('options_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('observations', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.FloatField()),
                ('total_discount', models.FloatField()),
                ('total_shipping', models.FloatField()),
                ('total_products', models.FloatField()),
                ('order_amount', models.FloatField()),
                ('prepaid_amount', models.FloatField()),
                ('pending_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('api_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
            ],
        ),
    ]
