# Generated by Django 4.1.5 on 2023-01-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('api_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationtransaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_transaction.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='benefits',
            field=models.ManyToManyField(to='api_transaction.benefit'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_transaction.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_transaction.delivery'),
        ),
        migrations.AddField(
            model_name='sale',
            name='fees',
            field=models.ManyToManyField(to='api_transaction.fee'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payments',
            field=models.ManyToManyField(to='api_transaction.payment'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='api_transaction.ProductSale', to='api_transaction.product'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_transaction.product'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_transaction.sale'),
        ),
        migrations.AddField(
            model_name='ifood',
            name='ifood_client_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_transaction.ifoodclient'),
        ),
        migrations.AddField(
            model_name='ifood',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_transaction.transaction'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_transaction.address'),
        ),
    ]
