# Generated by Django 4.1.5 on 2023-01-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transaction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
