# Generated by Django 4.1.4 on 2022-12-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_document", models.CharField(max_length=14)),
                ("integration_name", models.CharField(max_length=100)),
                ("integration_api_key", models.CharField(max_length=100)),
            ],
        ),
    ]
