# Generated by Django 4.1.4 on 2022-12-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_userclient_user_document"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="client_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="user.client"
            ),
        ),
    ]
