# Generated by Django 4.1.5 on 2023-01-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='client_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.client'),
        ),
    ]
