# Generated by Django 4.1.5 on 2023-01-09 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='client_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.client'),
        ),
        migrations.AlterField(
            model_name='integrationtransaction',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_transaction', to='integrations.integration'),
        ),
    ]
