# Generated by Django 4.1.5 on 2023-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integration_client_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='integration_client_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
